version: "3.8"
services:
  fyrebrick:
    image: ghcr.io/fyrebrick/fyrebrick:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
    depends_on: 
      - fyrebrick-updater-api
      - fyrebrick-updater
      - mongo
      - redis
    networks:
      - fyrebrick-net
    restart: unless-stopped
  fyrebrick-updater-api:
    image: ghcr.io/fyrebrick/fyrebrick-updater-api:latest
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - redis
    networks: 
      - fyrebrick-net
    restart: unless-stopped
  fyrebrick-updater:
    image: ghcr.io/fyrebrick/fyrebrick-updater:latest
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - redis
    networks: 
      - fyrebrick-net
    restart: unless-stopped
  mongo:
    image: registry.hub.docker.com/library/mongo
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
    networks:
      - fyrebrick-net
  redis:
    image: registry.hub.docker.com/library/redis
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
    networks:
      - fyrebrick-net
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
    networks:
      - fyrebrick-net
    depends_on:
      - mongo
    restart: unless-stopped
networks:
  fyrebrick-net: